# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8065e8f178f4eac7a7672e79b6cd24a7462887e93185f548db7a450628e152f856642ff252db1a007f6ab8516b731d6d381420c3d1a4e836243521c9a66ec234

test:
  secret_key_base: 35ae846f345808b0fbf4185022e7bc4e24919b7dd34f91e3772b8b36e945ae70f8cc525011b7874d0bacd2328a861f5515a53fc6ccc903ecc308b6d6be540fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
